services:
  postgres_dev:
    image: postgres:15-alpine
    container_name: core_platform_api_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - dev_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  redis_dev:
    image: redis:7-alpine
    container_name: core_platform_api_redis
    command: ['redis-server', '--appendonly', 'yes']
    ports:
      - '6379:6379'
    volumes:
      - redis_data_dev:/data
    networks:
      - dev_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

  nginx_proxy:
    image: nginx:alpine
    container_name: core_platform_api_nginx
    ports:
      - '8080:80'
    volumes:
      - ./ops/local-nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - dev_network
    restart: unless-stopped

volumes:
  postgres_data_dev:
  redis_data_dev:

networks:
  dev_network:
    driver: bridge
