export const AUTH_TOKENS = {
  AUTH_PROVIDER: Symbol('AUTH_PROVIDER'),
  CURRENT_SESSION_PROVIDER: Symbol('CURRENT_SESSION_PROVIDER'),
  AUTH_EMAIL_SENDER: Symbol('AUTH_EMAIL_SENDER'),
  AUTH_CONFIG: Symbol('AUTH_CONFIG'),
  SESSION_TRACKER: Symbol('SESSION_TRACKER'),
} as const;
