export const RBAC_TOKENS = {
  ROLE_REPOSITORY: Symbol('RBAC.ROLE_REPOSITORY'),
  PERMISSION_REPOSITORY: Symbol('RBAC.PERMISSION_REPOSITORY'),
  GRANTS_REPOSITORY: Symbol('RBAC.GRANTS_REPOSITORY'),
} as const;
